apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-rbac-cm.yaml
  - patches/argocd-redis-ha-haproxy.yaml
  - patches/argocd-server.yaml
  - patches/argocd-repo-server.yaml